repos:
  - repo: https://github.com/prettier/prettier.git
    rev: 1.19.1
    hooks:
      - id: prettier
        args: [--single-quote] #list of args like '--single-quote', '--jsx-bracket-same-line', '--print-width 120', '--no-bracket-spacing'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: [--maxkb=3000]
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.1
    hooks:
      #      - id: git-check # Configure in .gitattributes
      - id: markdownlint # Configure in .mdlrc
        args: [-r, '~MD013,~MD004']
      - id: require-ascii
      - id: shellcheck
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.2.0 # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        args:
          [
            --quiet,
            --format,
            compact,
            --ignore-pattern,
            '**/dist/',
            --ext,
            js,
            --ext,
            json,
            --fix,
          ]
